# Generated by Django 5.2.4 on 2025-07-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Auth_app', '0002_post_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
