# Generated by Django 5.2.4 on 2025-07-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Auth_app', '0003_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
    ]
