# Generated by Django 5.2.4 on 2025-07-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Auth_app', '0004_remove_userprofile_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
